export const types  = {
  GET_HEROES_ASYNC:'GET_HEROES_ASYNC',
  SET_IS_HEROES_LOADING:'SET_IS_HEROES_LOADING',
  SET_IS_HEROES_ERROR:'SET_IS_HEROES_ERROR',
  SET_HEROES:'SET_HEROES',

  GET_FILTERED_HEROES_ASYNC:'GET_FILTERED_HEROES_ASYNC',
  SET_IS_FILTERED_HEROES_LOADING:'SET_IS_FILTERED_HEROES_LOADING',
  SET_IS_FILTERED_HEROES_ERROR:'SET_IS_FILTERED_HEROES_ERROR',
  SET_FILTERED_HEROES:'SET_FILTERED_HEROES',
}
